version: '3.8'

services:
  backend:
    build: ./backend
    command: /start
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_API_ENDPOINT=localhost:8000